### ISSUE TITLE
🤓🤓🤓

### ISSUE THREAD

**Issue by gaouservbf** [Tarvey/AuroraKernel#1]
iT hAs no aPp loaDER

*This is a joke dont take it seriously*

**Comment by Tarvey** [comment]
will take seriously, will implement in about 3-4 business decades

**Comment by gaouservbf** [comment]
My man said 150/7 to 200/7 business days, bro is doing repeating decimal calculations that will destroy VB6 with a memory overflow, next time do irrational number business decades

**Comment by gaouservbf** [comment]
Time traveler speaking: it has been √950 irrational years and the kernel is still only able to load apps from .h precompiled into the kernel
